useTabs = true
tabWidth = 4
semi = true
singleQuote = true
jsxSingleQuote = true
trailingComma = "es5"
plugins = ["@ianvs/prettier-plugin-sort-imports"]
importOrder = ["^react.*$", "", "<THIRD_PARTY_MODULES>", "", "^@/.*$", "^src/.*", "", "^(\\.)?\\./(?!.*\\.s?css$).*", "", "\\.s?css$"]
importOrderTypeScriptVersion = '5.0.0'
